[package]
name = "ockam_command"
version = "0.3.1-dev"
edition = "2021"
license = "Apache-2.0"
publish = false
rust-version = "1.56.0"

[[bin]]
name = "ockam-cli"

[dependencies]
bunt = "0.2.6"
clap = { version = "3.0.4", features = ["derive"] }
comfy-table = "5.0.0"
config = { version = "0.11.0", features = ["toml"] }
ctrlc = "3.2.1"
dotenv = "0.15.0"
exitcode = "1.1.2"
human-panic = "1.0.3"
indicatif = "0.16.2"
log = "0.4.14"
ockam = { version = "^0.43.0-dev", path = "../ockam" }
serde = "1.0.130"
env_logger = "0.9.0"
thiserror = "1.0.30"
